services:
  - type: web
    name: piratao-do-mp3
    runtime: node
    buildCommand: bash render-build.sh
    startCommand: node artifacts/api-server/dist/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
